const cardImages = [
    { matched: false, "src": "/img/abduction.svg", alt: "abduction-icon" },
    { matched: false, "src": "/img/alien-1.svg", alt: "alien-icon" },
    { matched: false, "src": "/img/alien-angry.svg", alt: "alien-angry-icon" },
    { matched: false, "src": "/img/alien-grin.svg", alt: "alien-grin-icon" },
    { matched: false, "src": "/img/alien-pixel-1.svg", alt: "alien-pixel-1-icon" },
    { matched: false, "src": "/img/alien-pixel-2.svg", alt: "alien-pixel-2-icon" },
    { matched: false, "src": "/img/alien-sad.svg", alt: "alien-sad-icon" },
    { matched: false, "src": "/img/alien-sleep.svg", alt: "alien-sleep-icon" },
    { matched: false, "src": "/img/asteroid-1.svg", alt: "asteroid-1-icon" },
    { matched: false, "src": "/img/asteroid-2.svg", alt: "asteroid-2-icon" },
    { matched: false, "src": "/img/astronaut-1.svg", alt: "astronaut-1-icon" },
    { matched: false, "src": "/img/astronaut-2.svg", alt: "astronaut-2-icon" },
    { matched: false, "src": "/img/attack-ball.svg", alt: "attack-ball-icon" },
    { matched: false, "src": "/img/capsule.svg", alt: "capsule-icon" },
    { matched: false, "src": "/img/earth.svg", alt: "earth-icon" },
    { matched: false, "src": "/img/explorer.svg", alt: "explorer-icon" },
    { matched: false, "src": "/img/lightsaber.svg", alt: "lightsaber-icon" },
    { matched: false, "src": "/img/mars.svg", alt: "mars-icon" },
    { matched: false, "src": "/img/moon-1.svg", alt: "moon-1-icon" },
    { matched: false, "src": "/img/moon-2.svg", alt: "moon-2-icon" },
    { matched: false, "src": "/img/nebula.svg", alt: "nebula-icon" },
    { matched: false, "src": "/img/planetary.svg", alt: "planetary-icon" },
    { matched: false, "src": "/img/robot.svg", alt: "robot-icon" },
    { matched: false, "src": "/img/rocket.svg", alt: "rocket-icon" },
    { matched: false, "src": "/img/satellite-1.svg", alt: "satellite-1-icon" },
    { matched: false, "src": "/img/satellite-2.svg", alt: "satellite-2-icon" },
    { matched: false, "src": "/img/space-base.svg", alt: "space-base-icon" },
    { matched: false, "src": "/img/space-shuttle-1.svg", alt: "space-shuttle-1-icon" },
    { matched: false, "src": "/img/space-shuttle-2.svg", alt: "space-shuttle-2-icon" },
    { matched: false, "src": "/img/sun.svg", alt: "sun-icon" },
    { matched: false, "src": "/img/telescope.svg", alt: "telescope-icon" },
    { matched: false, "src": "/img/ufo-1.svg", alt: "ufo-1-icon" },
    { matched: false, "src": "/img/ufo-2.svg", alt: "ufo-2-icon" },
  ]
  
export default cardImages
